config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    get "static_pages/home"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(index new show create edit update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save{self.email = email.downcase}
  validates :name, presence: true,
  length: {maximum: Settings.length.digit_50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
            length: {maximum: Settings.length.digit_50},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: true
  has_secure_password
  validates :password,
            presence: true,
            length: {minimum: Settings.length.digit_6},
            allow_nil: true

  class << self
    # returns the hash digest of the given string
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    # return a random token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # remember a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  # returns true if the given token matches the digest
  def authenticated? remember_token
    BCrypt::Password.new(remember_token).is_password?(remember_token)
  end

  # forgets a user
  def forget
    update_attribute :remember_digest, nil
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = t "email.account_activated"
      redirect_to user
    else
      flash[:danger] = t "email.invalid_activation"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def default_url_options
    {locale: I18n.locale}
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by email: params[:session][:email].downcase
    if @user&.authenticate params[:session][:password]
      log_in @user
      session_p[:remember_me] == Settings.check ? remember(user) : forget(user)
      redirect_back_or @user
    else
      flash.now[:danger] = t "flash.invalid_email_password_combination"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
    return if @user.present?

    flash[:danger] = t "flash.danger"
    redirect_to root_path
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "flash.success"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:success] = t "flash.profile_updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user&.destroy
      flash[:success] = t "flash.user_deleted"
    else
      flash[:danger] = t "flash.delete_fail"
    end
    redirect_to users_url
  end

  private

  def user_params
    params
      .require(:user).permit :name, :email, :password, :password_confirmation
  end

  # before filters
  # confirms a logged-in user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t "flash.please_login"
      redirect_to login_url
    end
  end

  # confirms the correct user
  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # confirms an admin user
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("title.base_title")
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the given user
  def log_in user
    session[:user_id] = user.id
  end

  # remember a user in a persistent session
  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # rerurns the current logged-in user (if any)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # returns true if the user is logged in, false otherwise
  def logged_in?
    current_user.present?
  end

  # forgets a persistent session
  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # logs out the current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # returns true if the given user is the current user
  def current_user? user
    user == current_user
  end

  # redirects to stored location (or to the default)
  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.orginal_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to t("title.sample_app"), root_path, id: "logo"%>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to t("title.home"), root_path%></li>
                <li><%= link_to t("title.help"), help_path%></li>

                <% if logged_in? %>
                    <li><%= link_to t("user"), users_path %></li>
                    <li class="dropdown">
                        <%= link_to "#", class: "dropdown-toggle","data-toggle": "dropdown" do %>
                            <%= t("title.account")%> 
                            <b class="caret"></b>
                        <% end %>
                        <ul class="dropdown-menu">
                            <li><%= link_to t("title.profile"), current_user %></li>
                            <li><%= link_to t("title.setting"), edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to t("title.logout"), logout_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to t("title.login"), login_path %></li>
                <% end %>

                <li><%= link_to t("title.english"), locale:"en" %></li>
                <li><%= link_to t("title.vietnamese"), locale:"vi" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "the_form_contains" %>
      <%= pluralize @user.errors.size, "error" %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title, t("title.help") %>
    <%= link_to "English", locale:"en" %>
    <%= link_to "Vietnamese", locale:"vi" %>
    <h1><%= t"title.help"%></h1>
    <p><%= t"static_pages.help.body_html"%></p><!DOCTYPE html>

app/views/static_pages/home.html.erb
<% provide :title, t("title.home") %>
<div class="center jumbotron">
    <h1><%= t"title.home"%></h1>
    <h2><%= t"static_pages.home.body_html"%></h2>
    <%= link_to t("static_pages.sign_up"), signup_path, class: "btn btn-lg btn-primary"%>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: @user %>

  <%= f.label :name, t("title.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t("title.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("title.password_confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
    |    <%= link_to t("title.delete"), user, method: :delete, data: {confirm: t("title.you_sure")} %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, t("title.edit_user")) %>
<% provide(:button_text, t("title.save_changes")) %>
<h1><%= t("title.update_user")%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank"><%= t("title.change")%></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t("title.all_users")) %>
<h1><%= t("title.all_users")%></h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t("static_pages.sign_up") %>
<% provide :button_text, t("title.create_my_account") %>
<h1><%= t("title.sign_up")%></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>, <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>
  